#!/usr/bin/env python3
import yaml, json, sys
sys.stdout.write(json.dumps(yaml.safe_load(sys.stdin), sort_keys=True, indent=2))
##!/bin/bash
#cat -|
    #env PYTHONIOENCODING="UTF-8" python -c 'import sys, yaml, json; sys.stdout.write(yaml.safe_dump(json.loads(sys.stdin.read()), indent=2, allow_unicode=True, default_flow_style=False))'
