#!/bin/sh

amixer -c 0 -q set Master 3%- unmute || true

SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
#pactl -- set-sink-volume $SINK -3%
pamixer -ud 3
